[connections.snowflake]
account = "VMKWFSX-EXB17472"
user = "ABDIHAKIMABDALLA"
password = "JohnjohnJimjim237*"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
